#!/bin/bash

# Installs the "edge" build of onctl: an unsigned snapshot built from the
# tip of main on every push (see .github/workflows/edge.yml), published as
# a single rolling prerelease at a fixed tag rather than a versioned one.
# Linux and macOS -- the edge workflow does not build Windows binaries.

set -euo pipefail

# Repository details
REPO="cdalar/onctl"
GITHUB="https://github.com"
TAG="edge"

# Determine system architecture
architecture=$(uname -m)
case $architecture in
    x86_64)
        arch="amd64"
        ;;
    arm64*|aarch64*)
        arch="arm64"
        ;;
    *)
        echo "Error: Unsupported architecture: $architecture"
        exit 1
        ;;
esac

# Determine operating system
os=$(uname -s)
case $os in
    Linux)
        os="linux"
        extension=".tar.gz"
        unzip_command="tar zxvf"
        ;;
    Darwin)
        os="darwin"
        extension=".tar.gz"
        unzip_command="tar zxvf"
        ;;
    CYGWIN*|MINGW32*|MSYS*|MINGW*)
        echo "Error: no edge build is published for Windows -- download a tagged release from the releases page instead."
        exit 1
        ;;
    *)
        echo "Error: Unsupported operating system: $os"
        exit 1
        ;;
esac

echo "Installing onctl edge build ($os/$arch) from the '$TAG' release"

# Construct download URL -- must match .goreleaser.edge.yml's archive name_template
download_url="$GITHUB/$REPO/releases/download/$TAG/onctl-${os}-${arch}${extension}"
archive="onctl-${os}-${arch}-${TAG}${extension}"

# Download the binary. --fail makes curl exit non-zero on an HTTP error
# response (e.g. a stale/missing asset) instead of saving the error page as
# if it were the archive; set -e above then stops the script right here
# instead of it reaching the "complete" message with no usable binary.
echo "Downloading onctl from $download_url"
curl -fL "$download_url" -o "$archive"

echo "Extracting $archive"
$unzip_command "$archive" onctl

# Install shell tab completion (subcommands, flags, VM names for ssh/
# destroy/port-forward, instance sizes) for the shell in $SHELL -- this
# script itself always runs under bash via `curl | bash`, so $SHELL is
# the user's login shell, not ours. The completion script is generated by
# the binary we just extracted, so it always matches its version. Set
# ONCTL_NO_COMPLETION=1 to skip this step entirely.
install_completion() {
    local shell_name data_dir file rc
    shell_name=$(basename "${SHELL:-}")
    data_dir="${XDG_DATA_HOME:-$HOME/.local/share}"

    case $shell_name in
        bash)
            # bash-completion v2's per-user directory, lazy-loaded on the
            # first <TAB> after `onctl`...
            file="$data_dir/bash-completion/completions/onctl"
            rc="$HOME/.bashrc"
            ;;
        zsh)
            file="$data_dir/zsh/site-functions/_onctl"
            rc="$HOME/.zshrc"
            ;;
        fish)
            # fish autoloads this directory; no rc change needed.
            file="${XDG_CONFIG_HOME:-$HOME/.config}/fish/completions/onctl.fish"
            rc=""
            ;;
        *)
            echo "Skipping shell completion: unrecognized shell '${shell_name:-unknown}'."
            echo "Run 'onctl completion --help' to set it up by hand."
            return 0
            ;;
    esac

    mkdir -p "$(dirname "$file")"
    # -s: releases before the completion command stopped needing an
    # initialized .onctl directory exit 0 here without printing a script.
    if ! ./onctl completion "$shell_name" > "$file" || [ ! -s "$file" ]; then
        echo "Warning: could not generate $shell_name completion; skipping."
        rm -f "$file"
        return 0
    fi
    echo "Installed $shell_name completion to $file"

    # ...but plenty of setups (no bash-completion package, oh-my-bash, a
    # zsh without that directory on its fpath) never look there, so also
    # source it from the rc file -- once, and harmless if both happen.
    # zsh needs compinit to have run first (compdef must exist), which is
    # why the line goes at the end of .zshrc and checks for it.
    if [ -n "$rc" ] && ! grep -qsF "$file" "$rc"; then
        {
            echo ""
            echo "# onctl shell completion (added by onctl.sh/get.sh)"
            if [ "$shell_name" = "zsh" ]; then
                echo "(( \$+functions[compdef] )) && [ -r \"$file\" ] && source \"$file\""
            else
                echo "[ -r \"$file\" ] && source \"$file\""
            fi
        } >> "$rc"
        echo "Added a line to $rc to load it -- open a new terminal to use it."
    fi
}

if [ -z "${ONCTL_NO_COMPLETION:-}" ]; then
    install_completion
fi

echo "Download and unzip complete. onctl binary is in the current directory."
