version: 2
project_name: onctl

signs:
  - artifacts: checksum

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - binary: onctl
    id: onctl-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s -X 'github.com/cdalar/onctl/cmd.Version=v{{.Version}}-{{.ShortCommit}}'

  - binary: onctl
    id: onctl-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s -X 'github.com/cdalar/onctl/cmd.Version=v{{.Version}}-{{.ShortCommit}}'

  - binary: onctl
    id: onctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64 # M1 Chip
    ldflags:
      - -w -s -X 'github.com/cdalar/onctl/cmd.Version=v{{.Version}}-{{.ShortCommit}}'
    # hooks:
    #   post: ["gon gon/config-{{.Arch}}.json"]


archives:
  - id: repl
    name_template: "{{ .ProjectName }}-{{.Os}}-{{.Arch}}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    # files:
    #   - non-existent*

checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: cdalar
    name: onctl
  prerelease: auto

brews:
  - repository:
      owner: cdalar
      name: homebrew-tap
    description: onctl
