site_name: onctl
repo_url: https://github.com/cdalar/onctl
theme:
  name: material
  language: en
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Templates: templates.md
  # - Guides:
  #   - 'Installation': guides/installation.md
  #   - 'Configuration': guides/configuration.md
  #   - 'Usage': guides/usage.md
  #   - 'Development': guides/development.md
markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
