site_name: onctl
repo_url: https://github.com/cdalar/onctl
theme:
  name: material
  language: en
markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
