name: lint

permissions: 
  contents: read

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  workflow_call:

jobs:
  run:
    name: Lint
    runs-on: onctl-4
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Show machine
        run: |
          lsb_release -a
          lscpu | grep -E "Model name|^CPU\(s\)|Thread|Core"
          free -h
          df -h /
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version: 'stable'
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: latest
          args: --timeout 5m
